### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by hunterwilhelm** [gschier/insomnia-plugin-path-parameters#12]
I have checked that I have installed v1.0.3 and it doesn't seem to be working.
![Screen Shot 2022-03-16 at 4 32 02 PM](https://user-images.githubusercontent.com/71348224/158702374-517ca6e9-00ba-4172-b808-bdd17a53d5e4.png)
![Screen Shot 2022-03-16 at 4 33 49 PM](https://user-images.githubusercontent.com/71348224/158702433-3183dce1-c9ff-4d0d-b1d0-5a5fc9a9da6e.png)

**Comment by jkmartindale** [comment]
The plugin is working for me, though as a heads up URL encoding does not happen for parameters substituted by the plugin. Here's an illustration using a site that echoes back the entire path/query string you give it:

![GET request to https://echo.jkmartindale.dev/:foo with foo set to "1/2STROSB" resulting in the output "/1/2STROSB"](https://user-images.githubusercontent.com/11380394/158703280-2ff71833-7e43-4ef4-8302-b241274c5467.png)

For debugging parameter substitutions it's helpful to check the **Timeline** tab and make sure the request ends up the way you expect:

![Insomnia Timeline tab showing a GET request for /1/2STROSB](https://user-images.githubusercontent.com/11380394/158703432-58d72e4e-8a4f-48dc-8bbe-29c2b43c804f.png)

**Comment by hunterwilhelm** [comment]
Oh I see, thanks! I was running into two problems actually, the first was visual like we discussed but the second is that spring boot doesn't allow encoded slashes as parameters.
