### ISSUE TITLE
Autoreplacement didn't works

### ISSUE THREAD

**Issue by DavidExtern** [gschier/insomnia-plugin-path-parameters#2]
When I using your plugin, it didn't work

I put the key ":id" in my url and the associate value in query tab "id = 1", there is no replacement. It's add the query as parameter.

**Comment by chaosKP** [comment]
It does work, just the URL preview is wrong (https://github.com/gschier/insomnia-plugin-path-parameters/issues/3)

**Comment by DavidExtern** [comment]
Hi @chaosKP,

Thank you for your feedback. Here the screenshot :

![image](https://user-images.githubusercontent.com/39304470/83005305-edeeea00-a010-11ea-93e8-1a51c7c0d5f3.png)

**Comment by chaosKP** [comment]
Hm,
works for me:
![Screenshot](https://user-images.githubusercontent.com/60601974/83007565-2b08ab80-a014-11ea-8262-d2975b93b0c7.png)

Maybe the plugin is not enabled (Application -> Preferences -> Plugins)?
Else it could be because of the SSL config, which would be rather strange.

**Comment by DavidExtern** [comment]
It's very weird... The plugin is activate in the settings but it's not work like you... (sorry for preivous capture I put the valeur into header instead of query
![image](https://user-images.githubusercontent.com/39304470/83013252-fb11d600-a01c-11ea-94ea-f601178413e1.png)

**Comment by chaosKP** [comment]
Hm. maybe the installation is faulty. Did you try deleting and reinstalling? I installed it via the "Install in Core" from this site: https://insomnia.rest/plugins/insomnia-plugin-path-parameters.

**Comment by DavidExtern** [comment]
Point taken. After deleting and reinstalling it's work. 
Thank you for your useful help :)
