### ISSUE TITLE
Wrong Url preview

### ISSUE THREAD

**Issue by chaosKP** [gschier/insomnia-plugin-path-parameters#3]
if I specify an URL with a variable like `https://localhost:8080/:site` and add the `site = 3` query variable, the URL preview shows: `https://localhost:8080/:site?site=3`.
If I send the request it is correctly sent as `https://localhost:8080/3`.

**Comment by develohpanda** [comment]
Screenshot for reference:
<img width="988" alt="image" src="https://user-images.githubusercontent.com/4312346/93032935-30a00500-f688-11ea-8502-90ee2d7d8f3a.png">

**Comment by zigfreid5** [comment]
This plugin is implemented as a request hook but it should really be built into insomnia. As a plugin it's not (currently) possible for the url preview to be updated correctly.

**Comment by gschier** [comment]
Correct, this is not possible with the current plugin API. Closing now
