### ISSUE TITLE
Feature: default values for path parameters

### ISSUE THREAD

**Issue by chaosKP** [gschier/insomnia-plugin-path-parameters#5]
Idea 1:
It would be cool if the replacer would also look inside the environment to check if there is a value for the variable and use this if none is present inside the query variables.

Idea 2:
Or to define more than one query variable with the same name and pick the latest one.
The first one uses the definition from the environment and the second one overwrites this.
I tested this, currently only the first one is used for the replacement and the second one is completly ignored (not even used as a query parameter).

**Comment by gschier** [comment]
That seems a bit out of scope (too specific of a feature) for this plugin but feel free to fork it and create a new one if you'd like.
