### ISSUE TITLE
Plugin page on insomnia.rest lists wrong plugin name.

### ISSUE THREAD

**Issue by rezrov** [gschier/insomnia-plugin-path-parameters#7]
The instructions at https://insomnia.rest/plugins/insomnia-plugin-path-parameters show the plugin name as "insomnia-plugin-graphql-get", which is incorrect and does not match the README in this repo.

<img width="684" alt="Screen Shot 2020-09-10 at 1 57 55 PM" src="https://user-images.githubusercontent.com/729823/92777072-d6443300-f36d-11ea-9d40-3e7f58b77e75.png">

**Comment by gschier** [comment]
Thanks for reporting this! I had forgotten to publish the latest release to NPM
