### ISSUE TITLE
Url rewrited in Url Preview

### ISSUE THREAD

**Issue by GianlucaCr** [gschier/insomnia-plugin-path-parameters#9]
Could you preview the url in the url preview box, to confirm the correct replacement?

**Comment by gschier** [comment]
Unfortunately the Insomnia plugin system doesn't have a hook for this. Perhaps create a new issue on the Insomnia repo to request the feature?

**Comment by bruno-robert** [comment]
Related Insomnia [issue ( URL preview not showing real URL when plugins modifies it #5810 )](https://github.com/Kong/insomnia/issues/5810). 

Hopefully this gets fixed soon 😄
